version: "2"

linters:
  # Use default linters (errcheck, govet, ineffassign, staticcheck, unused)
  default: standard
  # Enable human-readable exclusion presets including std-error-handling
  # which excludes common error handling patterns like Close()
  exclusions:
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      # Ignore errcheck in test files - test code often has best-effort operations
      - linters:
          - errcheck
        path: "_test\\.go"
  settings:
    errcheck:
      # Additional functions to exclude from checking
      exclude-functions:
        - (*github.com/ghostunnel/ghostunnel/certloader.spiffeTLSConfigSource).Close
