version: "2"
linters:
  default: standard
exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
    paths:
      - "vendor/*"
