# Dockerfile for ghostunnel/ghostunnel built on Debian.
#
# To build this image:
#     docker build -t ghostunnel/ghostunnel .
#
# To run ghostunnel from the image (for example):
#     docker run --rm ghostunnel/ghostunnel --version

FROM golang:1.25-bookworm AS build

# Dependencies
RUN apt update && apt install -y gcc make git

# Copy source
COPY . /go/src/github.com/ghostunnel/ghostunnel

# Build
RUN cd /go/src/github.com/ghostunnel/ghostunnel && \
    GOFLAGS="-tags=nopkcs11" make clean ghostunnel && \
    cp ghostunnel /usr/bin/ghostunnel

# Create a multi-stage build with the binary
FROM gcr.io/distroless/base-nossl:nonroot

COPY --from=build /usr/bin/ghostunnel /usr/bin/ghostunnel

ENTRYPOINT ["/usr/bin/ghostunnel"]
