# Dockerfile for ghostunnel/ghostunnel built on Debian.
#
# To build this image:
#     docker build -t ghostunnel/ghostunnel .
#
# To run ghostunnel from the image (for example):
#     docker run --rm ghostunnel/ghostunnel --version

FROM golang:1.24-bookworm AS build

# Dependencies
RUN apt update && apt install -y gcc libtool make git

# Copy source
COPY . /go/src/github.com/ghostunnel/ghostunnel

# Build
RUN cd /go/src/github.com/ghostunnel/ghostunnel && \
    GO111MODULE=on make clean ghostunnel && \
    cp ghostunnel /usr/bin/ghostunnel

# Create a multi-stage build with the binary
FROM debian:bookworm-slim

RUN apt update && apt install -y --no-install-recommends libtool curl && rm -rf /var/lib/apt/lists/*
COPY --from=build /usr/bin/ghostunnel /usr/bin/ghostunnel

ENTRYPOINT ["/usr/bin/ghostunnel"]
