# Dockerfile for ghostunnel/ghostunnel built on Debian.
#
# To build this image:
#     docker build -t ghostunnel/ghostunnel .
#
# To run ghostunnel from the image (for example):
#     docker run --rm ghostunnel/ghostunnel --version

FROM golang:1.26-bookworm AS build

# Dependencies
RUN apt update && apt install -y gcc git

# Copy source
COPY . /go/src/github.com/ghostunnel/ghostunnel

# Install mage and build
RUN cd /go/src/github.com/ghostunnel/ghostunnel && \
    go install github.com/magefile/mage@latest && \
    export PATH=$PATH:$(go env GOPATH)/bin && \
    GOFLAGS="-tags=nopkcs11" mage -v go:build && \
    cp ghostunnel /usr/bin/ghostunnel

# Create a multi-stage build with the binary
FROM gcr.io/distroless/base-nossl:nonroot

COPY --from=build /usr/bin/ghostunnel /usr/bin/ghostunnel

ENTRYPOINT ["/usr/bin/ghostunnel"]
